[project]
name = "kb-server"
version = "0.1.0"
description = "Knowledge base http and document task service package."
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.111,<1.0",
    "funasr>=1.3,<2.0",
    "httpx[socks]==0.28.1",
    "leary-logging",
    "knowledge-base",
    "minio>=7.2.20",
    "oss2>=2.18.6",
    "pika==1.3.2",
    "prometheus-client>=0.20,<1.0",
    "pydantic>=2.12,<2.13",
    "pymupdf>=1.26.7",
    "requests>=2.32,<3.0",
    "sqlalchemy>=2.0,<3.0",
    "task-events",
    "torch==2.6.*",
    "torchaudio==2.6.*",
    "uvicorn>=0.30,<1.0",
    "yt-dlp"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["kb_server*"]
namespaces = true
