# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from usage_control.grpc.usage.v1 import usage_service_pb2 as usage_dot_v1_dot_usage__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in usage/v1/usage_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsageServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveUsage = channel.unary_unary(
                '/usage.v1.UsageService/ReserveUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.ReserveUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.ReserveUsageResponse.FromString,
                _registered_method=True)
        self.CommitUsage = channel.unary_unary(
                '/usage.v1.UsageService/CommitUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.CommitUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitUsageResponse.FromString,
                _registered_method=True)
        self.ReleaseUsage = channel.unary_unary(
                '/usage.v1.UsageService/ReleaseUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.ReleaseUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.ReleaseUsageResponse.FromString,
                _registered_method=True)
        self.GetCurrentCycleUsage = channel.unary_unary(
                '/usage.v1.UsageService/GetCurrentCycleUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageResponse.FromString,
                _registered_method=True)
        self.GetRollingUsage = channel.unary_unary(
                '/usage.v1.UsageService/GetRollingUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.GetRollingUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.GetRollingUsageResponse.FromString,
                _registered_method=True)


class UsageServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReserveUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentCycleUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRollingUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.ReserveUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.ReserveUsageResponse.SerializeToString,
            ),
            'CommitUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.CommitUsageResponse.SerializeToString,
            ),
            'ReleaseUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.ReleaseUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.ReleaseUsageResponse.SerializeToString,
            ),
            'GetCurrentCycleUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentCycleUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageResponse.SerializeToString,
            ),
            'GetRollingUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRollingUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.GetRollingUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.GetRollingUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usage.v1.UsageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usage.v1.UsageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsageService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserveUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageService/ReserveUsage',
            usage_dot_v1_dot_usage__service__pb2.ReserveUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.ReserveUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageService/CommitUsage',
            usage_dot_v1_dot_usage__service__pb2.CommitUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.CommitUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageService/ReleaseUsage',
            usage_dot_v1_dot_usage__service__pb2.ReleaseUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.ReleaseUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentCycleUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageService/GetCurrentCycleUsage',
            usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.GetCurrentCycleUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRollingUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageService/GetRollingUsage',
            usage_dot_v1_dot_usage__service__pb2.GetRollingUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.GetRollingUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UsageControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentPolicy = channel.unary_unary(
                '/usage.v1.UsageControlService/GetCurrentPolicy',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyResponse.FromString,
                _registered_method=True)
        self.OpenTurnLease = channel.unary_unary(
                '/usage.v1.UsageControlService/OpenTurnLease',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseResponse.FromString,
                _registered_method=True)
        self.CommitTurnCallUsage = channel.unary_unary(
                '/usage.v1.UsageControlService/CommitTurnCallUsage',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageResponse.FromString,
                _registered_method=True)
        self.CloseTurnLease = channel.unary_unary(
                '/usage.v1.UsageControlService/CloseTurnLease',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseResponse.FromString,
                _registered_method=True)
        self.AbortTurnLease = channel.unary_unary(
                '/usage.v1.UsageControlService/AbortTurnLease',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseResponse.FromString,
                _registered_method=True)
        self.GetTurnLease = channel.unary_unary(
                '/usage.v1.UsageControlService/GetTurnLease',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseResponse.FromString,
                _registered_method=True)
        self.ReserveSingleCall = channel.unary_unary(
                '/usage.v1.UsageControlService/ReserveSingleCall',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallResponse.FromString,
                _registered_method=True)
        self.CommitSingleCall = channel.unary_unary(
                '/usage.v1.UsageControlService/CommitSingleCall',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.CommitSingleCallRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitSingleCallResponse.FromString,
                _registered_method=True)
        self.ReleaseSingleCall = channel.unary_unary(
                '/usage.v1.UsageControlService/ReleaseSingleCall',
                request_serializer=usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallRequest.SerializeToString,
                response_deserializer=usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallResponse.FromString,
                _registered_method=True)


class UsageControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCurrentPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenTurnLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTurnCallUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTurnLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTurnLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTurnLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveSingleCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSingleCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSingleCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsageControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPolicy,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyResponse.SerializeToString,
            ),
            'OpenTurnLease': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenTurnLease,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseResponse.SerializeToString,
            ),
            'CommitTurnCallUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTurnCallUsage,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageResponse.SerializeToString,
            ),
            'CloseTurnLease': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTurnLease,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseResponse.SerializeToString,
            ),
            'AbortTurnLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTurnLease,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseResponse.SerializeToString,
            ),
            'GetTurnLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTurnLease,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseResponse.SerializeToString,
            ),
            'ReserveSingleCall': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSingleCall,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallResponse.SerializeToString,
            ),
            'CommitSingleCall': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSingleCall,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.CommitSingleCallRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.CommitSingleCallResponse.SerializeToString,
            ),
            'ReleaseSingleCall': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSingleCall,
                    request_deserializer=usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallRequest.FromString,
                    response_serializer=usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usage.v1.UsageControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usage.v1.UsageControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsageControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/GetCurrentPolicy',
            usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.GetCurrentPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenTurnLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/OpenTurnLease',
            usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.OpenTurnLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTurnCallUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/CommitTurnCallUsage',
            usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.CommitTurnCallUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseTurnLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/CloseTurnLease',
            usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.CloseTurnLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTurnLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/AbortTurnLease',
            usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.AbortTurnLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTurnLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/GetTurnLease',
            usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.GetTurnLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveSingleCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/ReserveSingleCall',
            usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.ReserveSingleCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSingleCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/CommitSingleCall',
            usage_dot_v1_dot_usage__service__pb2.CommitSingleCallRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.CommitSingleCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSingleCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usage.v1.UsageControlService/ReleaseSingleCall',
            usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallRequest.SerializeToString,
            usage_dot_v1_dot_usage__service__pb2.ReleaseSingleCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
